name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true
jobs:
  ci:
    if: ${{ !startsWith(github.ref, 'refs/tags') }}
    name: Build, Lint, Test
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Test/Lint Dependencies
        # Ensure that PyXA is installed as a test dependency
        run: |
          pip install pytest pytest-mock pylint
          pip install -e ".[test]"

      - name: Run Linter
        run: pylint plover_run_applescript

      - name: Run Tests
        run: pytest
