name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  # REF: https://github.com/pypa/gh-action-pypi-publish#usage
  pypi-publish:
    name: Build, Release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/plover-run-applescript/
    permissions:
      id-token: write
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # NOTE: Since the tests require PyXA, they cannot be run on a Linux
      # machine, so testing is skipped in release.

      - name: Install Build
        run: python -m pip install --upgrade build

      - name: Build
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  # REF: https://stackoverflow.com/questions/75679683/how-can-i-auto-generate-a-release-note-and-create-a-release-using-github-actions
  github-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs:
      - pypi-publish
    if: always() && needs.pypi-publish.result == 'success'
    permissions:
      contents: write
    steps:
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
            --repo="$GITHUB_REPOSITORY" \
            --title="$TAG" \
            --generate-notes
